# Generated by Django 4.2.6 on 2023-11-03 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_answer_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='score',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.answer'),
        ),
    ]
