# Generated by Django 4.2.6 on 2023-11-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_useranswer_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
